2.1

In [2]:
import numpy as np


def matrices_array(n):
    A = np.random.random((n,n)).astype(np.float64)
    B = np.random.random((n,n)).astype(np.float64)
    C= np.zeros_like(A)
    return A, B, C

def dgemm(A, B, C, n):
    for i in range(n):
        for j in range(n):
            for k in range(n):
                C[i][j] += A[i][k] * B[k][j]
    return C



n = 5
A, B, C = matrices_array(n)
print(f"A:\n{A}")
print(f"B:\n{B}")

C_result = dgemm(A, B, C, n)
print(f"C:\n{C_result}")


A:
[[0.39826042 0.65544076 0.48106205 0.88544675 0.11923474]
 [0.05516072 0.86348287 0.04908175 0.32487433 0.13282438]
 [0.14181894 0.71555884 0.53464954 0.06823784 0.53291105]
 [0.84246658 0.316167   0.2919461  0.7958124  0.3672937 ]
 [0.03702327 0.08216213 0.61802896 0.8005314  0.64330752]]
B:
[[0.50066934 0.45612161 0.47528245 0.15464013 0.61934265]
 [0.83554897 0.56283994 0.59893248 0.85286869 0.91562488]
 [0.77600957 0.08207941 0.95932393 0.75329592 0.13946612]
 [0.68349131 0.73691451 0.18276957 0.59987947 0.70105181]
 [0.37072863 0.9742554  0.66321394 0.31511748 0.41275184]]
C:
[[1.76975727 1.35871235 1.28425614 1.5517083  1.58384779]
 [1.058478   0.88400072 0.73793828 1.01868138 1.11421227]
 [1.32798736 1.08079242 1.37478341 1.24382201 1.08538177]
 [1.59262032 1.53046497 1.25888774 1.21298207 1.56148932]
 [1.35243206 1.33052772 1.23265934 1.22429728 1.01109423]]


Task 2.2

In [6]:
! python -m pytest -v dgemm.py

============================= test session starts =============================
platform win32 -- Python 3.9.10, pytest-8.3.4, pluggy-1.5.0 -- C:\Program Files\Python39\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\davii\OneDrive\Skrivbord\Assignment ll\Exercise 2
plugins: anyio-4.8.0
collecting ... collected 1 item

dgemm.py::test_dgemm PASSED                                              [100%]

============================== 1 passed in 0.22s ==============================


In [1]:
! python dgemm1.py

+------+-------------+------------+------------+------------+----------+---------------------+
| Size |    Method   | Avg Time   |  Min Time  |  Max Time  | Std Dev  |        FLOPS        |
+------+-------------+------------+------------+------------+----------+---------------------+
|  10  | dgemm_numpy |  0.000010  |  0.000002  |  0.000039  | 0.000015 |   206611570.247680  |
|  10  |  dgemm_list |  0.000143  |  0.000134  |  0.000159  | 0.000011 |   14023278.642548   |
|  10  | dgemm_array |  0.000212  |  0.000196  |  0.000253  | 0.000021 |    9412650.602408   |
| 100  | dgemm_numpy |  0.000230  |  0.000174  |  0.000303  | 0.000046 |  8697921196.837080  |
| 100  |  dgemm_list |  0.135920  |  0.127715  |  0.152192  | 0.008447 |   14714559.615303   |
| 100  | dgemm_array |  0.219767  |  0.207729  |  0.255554  | 0.018020 |    9100539.115937   |
| 1000 | dgemm_numpy |  0.019654  |  0.018847  |  0.021123  | 0.000776 | 101758902632.114426 |
| 1000 |  dgemm_list | 172.944428 | 170.119786 | 1

Small matrices (n < 10), excution times are stable (low std) since operations fit in CPU cash. 
Large matrices (n> 100), standard deviation increases due to cache misses, memory access overheads.
NumPy is the best choice in Average, min, max and Std time for performance and stability as it minimiez memory overheads. But in small size on Standard deviation show that list is good.  

The total number of operations for DGEMM is 2N^3. My CPU has clock speed= 1.90 GHz = 1.90 * 2^30 = 2,040,109,466.
For large matrices (N = 1000), dgemm_numpy is nearly 10,000x faster than dgemm_list or dgemm_array, and numpy achieves a performance far beyond the theoretical peak of the CPU. Measured FLOPS values show that numpy's performance increases with larger matrices, whereas the list and array implementations remain bottlenecked by poor optimization.
